spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081